import mongoose from "mongoose";
import dotenv from "dotenv";
import Item from "./models/item.js"; // Asegurate que la ruta sea correcta

dotenv.config();

const seedDB = async () => {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || "mongodb://localhost:27017/dnd-database"
    );

    const itemsData = [
      // ===========================================================================
      // 1. ARMAS (WEAPONS) - Tabla Pág. 215 (Manual 2024)
      // ===========================================================================

      // --- Armas Cuerpo a Cuerpo Sencillas ---
      {
        name: "Bastón",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 2, unit: "pp" },
        weight: 2,
        damage: { dice: "1d6", type: "Contundente" },
        properties: ["Versátil (1d8)"],
        masteryProperty: "Derribar",
        description: "Un palo largo de madera, a veces reforzado con hierro.",
      },
      {
        name: "Daga",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 2, unit: "po" },
        weight: 0.5,
        damage: { dice: "1d4", type: "Perforante" },
        properties: ["Arrojadiza", "Ligera", "Sutil"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Mellar",
        description: "Hoja corta y afilada, fácil de ocultar.",
      },
      {
        name: "Garrote",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 1, unit: "pp" },
        weight: 1,
        damage: { dice: "1d4", type: "Contundente" },
        properties: ["Ligero"],
        masteryProperty: "Ralentizar",
        description: "Un palo corto y grueso, a menudo de madera.",
      },
      {
        name: "Garrote grande",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 2, unit: "pp" },
        weight: 5,
        damage: { dice: "1d8", type: "Contundente" },
        properties: ["A dos manos"],
        masteryProperty: "Empujar",
        description: "Un garrote masivo que requiere dos manos.",
      },
      {
        name: "Hacha de mano",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 5, unit: "po" },
        weight: 1,
        damage: { dice: "1d6", type: "Cortante" },
        properties: ["Arrojadiza", "Ligera"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Molestar",
        description: "Un hacha pequeña equilibrada para ser lanzada.",
      },
      {
        name: "Hoz",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 1, unit: "po" },
        weight: 1,
        damage: { dice: "1d4", type: "Cortante" },
        properties: ["Ligera"],
        masteryProperty: "Mellar",
        description: "Herramienta de agricultura adaptada para el combate.",
      },
      {
        name: "Jabalina",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 5, unit: "pp" },
        weight: 1,
        damage: { dice: "1d6", type: "Perforante" },
        properties: ["Arrojadiza"],
        range: { normal: 9, long: 36 },
        masteryProperty: "Ralentizar",
        description: "Una lanza ligera diseñada para ser arrojada.",
      },
      {
        name: "Lanza",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 1, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d6", type: "Perforante" },
        properties: ["Arrojadiza", "Versátil (1d8)"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Debilitar",
        description: "Un asta con una punta afilada.",
      },
      {
        name: "Martillo ligero",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 2, unit: "po" },
        weight: 1,
        damage: { dice: "1d4", type: "Contundente" },
        properties: ["Arrojadizo", "Ligero"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Mellar",
        description: "Un martillo pequeño, útil como herramienta y arma.",
      },
      {
        name: "Maza",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 5, unit: "po" },
        weight: 2,
        damage: { dice: "1d6", type: "Contundente" },
        properties: [],
        masteryProperty: "Debilitar",
        description: "Un arma contundente con una cabeza pesada.",
      },

      // --- Armas a Distancia Sencillas ---
      {
        name: "Arco corto",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 25, unit: "po" },
        weight: 1,
        damage: { dice: "1d6", type: "Perforante" },
        properties: ["A dos manos", "Munición"],
        range: { normal: 24, long: 96 },
        masteryProperty: "Molestar",
        description: "Un arco pequeño y manejable.",
      },
      {
        name: "Ballesta ligera",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 25, unit: "po" },
        weight: 2.5,
        damage: { dice: "1d8", type: "Perforante" },
        properties: ["A dos manos", "Munición", "Recarga"],
        range: { normal: 24, long: 96 },
        masteryProperty: "Ralentizar",
        description: "Una ballesta de tamaño medio.",
      },
      {
        name: "Dardo",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 5, unit: "pc" },
        weight: 0.125,
        damage: { dice: "1d4", type: "Perforante" },
        properties: ["Arrojadizo", "Sutil"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Molestar",
        description: "Un pequeño proyectil puntiagudo.",
      },
      {
        name: "Honda",
        type: "Weapon",
        weaponCategory: "Simple",
        cost: { quantity: 1, unit: "pp" },
        weight: 0,
        damage: { dice: "1d4", type: "Contundente" },
        properties: ["Munición"],
        range: { normal: 9, long: 36 },
        masteryProperty: "Ralentizar",
        description: "Una tira de cuero para lanzar piedras.",
      },

      // --- Armas Cuerpo a Cuerpo Marciales ---
      {
        name: "Alabarda",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 20, unit: "po" },
        weight: 3,
        damage: { dice: "1d10", type: "Cortante" },
        properties: ["A dos manos", "Gran alcance", "Pesada"],
        masteryProperty: "Hender",
        description: "Un arma de asta larga con una hoja de hacha.",
      },
      {
        name: "Cimitarra",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 25, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d6", type: "Cortante" },
        properties: ["Ligera", "Sutil"],
        masteryProperty: "Mellar",
        description: "Una espada de hoja curva.",
      },
      {
        name: "Espada corta",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 1,
        damage: { dice: "1d6", type: "Perforante" },
        properties: ["Ligera", "Sutil"],
        masteryProperty: "Molestar",
        description: "Una espada de hoja recta y ligera.",
      },
      {
        name: "Espada larga",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 15, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d8", type: "Cortante" },
        properties: ["Versátil (1d10)"],
        masteryProperty: "Debilitar",
        description: "Una espada versátil usada a una o dos manos.",
      },
      {
        name: "Espadón",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 50, unit: "po" },
        weight: 3,
        damage: { dice: "2d6", type: "Cortante" },
        properties: ["A dos manos", "Pesada"],
        masteryProperty: "Rozar",
        description: "Una enorme espada que requiere gran fuerza.",
      },
      {
        name: "Estoque",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 25, unit: "po" },
        weight: 1,
        damage: { dice: "1d8", type: "Perforante" },
        properties: ["Sutil"],
        masteryProperty: "Molestar",
        description: "Una espada fina y punzante.",
      },
      {
        name: "Guja",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 20, unit: "po" },
        weight: 3,
        damage: { dice: "1d10", type: "Cortante" },
        properties: ["A dos manos", "Gran alcance", "Pesada"],
        masteryProperty: "Rozar",
        description: "Un arma de asta con una hoja curva.",
      },
      {
        name: "Hacha a dos manos",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 30, unit: "po" },
        weight: 3.5,
        damage: { dice: "1d12", type: "Cortante" },
        properties: ["A dos manos", "Pesada"],
        masteryProperty: "Hender",
        description: "Un hacha masiva capaz de partir escudos.",
      },
      {
        name: "Hacha de guerra",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 2,
        damage: { dice: "1d8", type: "Cortante" },
        properties: ["Versátil (1d10)"],
        masteryProperty: "Derribar",
        description: "Un hacha de combate versátil.",
      },
      {
        name: "Lanza de caballería",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 3,
        damage: { dice: "1d12", type: "Perforante" },
        properties: ["Gran alcance", "Pesada", "Especial"],
        masteryProperty: "Derribar",
        description:
          "Diseñada para usarse a caballo. A dos manos si no estás montado.",
      },
      {
        name: "Látigo",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 2, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d4", type: "Cortante" },
        properties: ["Gran alcance", "Sutil"],
        masteryProperty: "Ralentizar",
        description: "Un látigo largo de cuero.",
      },
      {
        name: "Lucero del alba",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 15, unit: "po" },
        weight: 2,
        damage: { dice: "1d8", type: "Perforante" },
        properties: [],
        masteryProperty: "Debilitar",
        description: "Una maza con pinchos.",
      },
      {
        name: "Mangual",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 1,
        damage: { dice: "1d8", type: "Contundente" },
        properties: [],
        masteryProperty: "Debilitar",
        description: "Una bola de metal unida a un mango por una cadena.",
      },
      {
        name: "Martillo de guerra",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 15, unit: "po" },
        weight: 2.5,
        damage: { dice: "1d8", type: "Contundente" },
        properties: ["Versátil (1d10)"],
        masteryProperty: "Empujar",
        description: "Un martillo pesado de combate.",
      },
      {
        name: "Maza a dos manos",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 5,
        damage: { dice: "2d6", type: "Contundente" },
        properties: ["A dos manos", "Pesada"],
        masteryProperty: "Derribar",
        description: "Un martillo gigante para aplastar.",
      },
      {
        name: "Pica",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 5, unit: "po" },
        weight: 9,
        damage: { dice: "1d10", type: "Perforante" },
        properties: ["A dos manos", "Gran alcance", "Pesada"],
        masteryProperty: "Empujar",
        description: "Una lanza extremadamente larga.",
      },
      {
        name: "Pico de guerra",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 5, unit: "po" },
        weight: 1,
        damage: { dice: "1d8", type: "Perforante" },
        properties: ["Versátil (1d10)"],
        masteryProperty: "Debilitar",
        description: "Un pico diseñado para perforar armaduras.",
      },
      {
        name: "Tridente",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 5, unit: "po" },
        weight: 2,
        damage: { dice: "1d8", type: "Perforante" },
        properties: ["Arrojadizo", "Versátil (1d10)"],
        range: { normal: 6, long: 18 },
        masteryProperty: "Derribar",
        description: "Una lanza de tres puntas.",
      },

      // --- Armas a Distancia Marciales ---
      {
        name: "Arco largo",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 50, unit: "po" },
        weight: 1,
        damage: { dice: "1d8", type: "Perforante" },
        properties: ["A dos manos", "Munición", "Pesada"],
        range: { normal: 45, long: 180 },
        masteryProperty: "Ralentizar",
        description: "Un arco grande de gran alcance.",
      },
      {
        name: "Ballesta de mano",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 75, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d6", type: "Perforante" },
        properties: ["Ligera", "Munición", "Recarga"],
        range: { normal: 9, long: 36 },
        masteryProperty: "Molestar",
        description: "Una ballesta pequeña que se puede disparar con una mano.",
      },
      {
        name: "Ballesta pesada",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 50, unit: "po" },
        weight: 9,
        damage: { dice: "1d10", type: "Perforante" },
        properties: ["A dos manos", "Munición", "Pesada", "Recarga"],
        range: { normal: 30, long: 120 },
        masteryProperty: "Empujar",
        description: "Una ballesta poderosa con mecanismo de torno.",
      },
      {
        name: "Cerbatana",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 10, unit: "po" },
        weight: 0.5,
        damage: { dice: "1", type: "Perforante" },
        properties: ["Munición", "Recarga"],
        range: { normal: 7.5, long: 30 },
        masteryProperty: "Molestar",
        description: "Un tubo para disparar dardos venenosos.",
      },
      {
        name: "Mosquete",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 500, unit: "po" },
        weight: 5,
        damage: { dice: "1d12", type: "Perforante" },
        properties: ["A dos manos", "Munición", "Recarga", "Pesada"],
        range: { normal: 12, long: 36 },
        masteryProperty: "Ralentizar",
        description: "Un arma de fuego de pólvora negra.",
      },
      {
        name: "Pistola",
        type: "Weapon",
        weaponCategory: "Marcial",
        cost: { quantity: 250, unit: "po" },
        weight: 1.5,
        damage: { dice: "1d10", type: "Perforante" },
        properties: ["Munición", "Recarga"],
        range: { normal: 9, long: 27 },
        masteryProperty: "Molestar",
        description: "Un arma de fuego de mano.",
      },

      // ===========================================================================
      // 2. ARMADURAS (ARMOR) - Tabla Pág. 221
      // ===========================================================================

      // --- Ligeras ---
      {
        name: "Armadura acolchada",
        type: "Armor",
        armorCategory: "Ligera",
        cost: { quantity: 5, unit: "po" },
        weight: 4,
        ac: { base: 11, addDex: true, maxDex: null },
        stealthDisadvantage: true,
        description: "Capas de tela acolchada.",
      },
      {
        name: "Armadura de cuero",
        type: "Armor",
        armorCategory: "Ligera",
        cost: { quantity: 10, unit: "po" },
        weight: 5,
        ac: { base: 11, addDex: true, maxDex: null },
        stealthDisadvantage: false,
        description: "Pechera y hombreras de cuero endurecido.",
      },
      {
        name: "Armadura de cuero tachonado",
        type: "Armor",
        armorCategory: "Ligera",
        cost: { quantity: 45, unit: "po" },
        weight: 6.5,
        ac: { base: 12, addDex: true, maxDex: null },
        stealthDisadvantage: false,
        description: "Cuero reforzado con remaches de metal.",
      },

      // --- Medias ---
      {
        name: "Armadura de pieles",
        type: "Armor",
        armorCategory: "Media",
        cost: { quantity: 10, unit: "po" },
        weight: 6,
        ac: { base: 12, addDex: true, maxDex: 2 },
        stealthDisadvantage: false,
        description: "Pieles gruesas y pelajes.",
      },
      {
        name: "Camisa de malla",
        type: "Armor",
        armorCategory: "Media",
        cost: { quantity: 50, unit: "po" },
        weight: 10,
        ac: { base: 13, addDex: true, maxDex: 2 },
        stealthDisadvantage: false,
        description: "Anillas de metal entrelazadas entre capas de tela.",
      },
      {
        name: "Cota de escamas",
        type: "Armor",
        armorCategory: "Media",
        cost: { quantity: 50, unit: "po" },
        weight: 22.5,
        ac: { base: 14, addDex: true, maxDex: 2 },
        stealthDisadvantage: true,
        description: "Escamas de metal sobre cuero.",
      },
      {
        name: "Coraza",
        type: "Armor",
        armorCategory: "Media",
        cost: { quantity: 400, unit: "po" },
        weight: 10,
        ac: { base: 14, addDex: true, maxDex: 2 },
        stealthDisadvantage: false,
        description: "Peto de metal con cuero flexible.",
      },
      {
        name: "Media armadura",
        type: "Armor",
        armorCategory: "Media",
        cost: { quantity: 750, unit: "po" },
        weight: 20,
        ac: { base: 15, addDex: true, maxDex: 2 },
        stealthDisadvantage: true,
        description: "Placas de metal que cubren la mayor parte del cuerpo.",
      },

      // --- Pesadas ---
      {
        name: "Cota guarnecida",
        type: "Armor",
        armorCategory: "Pesada",
        cost: { quantity: 30, unit: "po" },
        weight: 20,
        ac: { base: 14, addDex: false, maxDex: 0 },
        stealthDisadvantage: true,
        description: "Cuero con anillas de metal cosidas.",
      },
      {
        name: "Cota de malla",
        type: "Armor",
        armorCategory: "Pesada",
        cost: { quantity: 75, unit: "po" },
        weight: 27.5,
        ac: { base: 16, addDex: false, maxDex: 0 },
        strengthReq: 13,
        stealthDisadvantage: true,
        description: "Anillas de metal entrelazadas que cubren todo el cuerpo.",
      },
      {
        name: "Armadura de bandas",
        type: "Armor",
        armorCategory: "Pesada",
        cost: { quantity: 200, unit: "po" },
        weight: 30,
        ac: { base: 17, addDex: false, maxDex: 0 },
        strengthReq: 15,
        stealthDisadvantage: true,
        description: "Tiras verticales de metal sobre cuero.",
      },
      {
        name: "Armadura de placas",
        type: "Armor",
        armorCategory: "Pesada",
        cost: { quantity: 1500, unit: "po" },
        weight: 32.5,
        ac: { base: 18, addDex: false, maxDex: 0 },
        strengthReq: 15,
        stealthDisadvantage: true,
        description:
          "Placas de metal interconectadas que cubren todo el cuerpo.",
      },

      // --- Escudo ---
      {
        name: "Escudo",
        type: "Armor",
        armorCategory: "Escudo",
        cost: { quantity: 10, unit: "po" },
        weight: 3,
        ac: { base: 2, addDex: false, maxDex: 0 },
        stealthDisadvantage: false,
        description: "Hecho de madera o metal, se embraza en un brazo.",
      },

      // ===========================================================================
      // 3. HERRAMIENTAS (TOOLS)
      // ===========================================================================
      {
        name: "Herramientas de ladrón",
        type: "Tool",
        cost: { quantity: 25, unit: "po" },
        weight: 0.5,
        description:
          "Ganzúas, espejo, limas y tenazas. Necesarias para desactivar trampas y abrir cerraduras.",
      },
      {
        name: "Instrumento musical",
        type: "Tool",
        cost: { quantity: 35, unit: "po" },
        weight: 1,
        description:
          "Varios tipos: Laúd, Flauta, Tambor, Lira, etc. Esencial para bardos.",
      },
      {
        name: "Útiles de herborista",
        type: "Tool",
        cost: { quantity: 5, unit: "po" },
        weight: 1.5,
        description:
          "Para identificar plantas y crear pociones de curación o antitoxinas.",
      },
      {
        name: "Útiles de envenenador",
        type: "Tool",
        cost: { quantity: 50, unit: "po" },
        weight: 1,
        description: "Permite crear y aplicar venenos de forma segura.",
      },
      {
        name: "Herramientas de artesano",
        type: "Tool",
        cost: { quantity: 15, unit: "po" },
        weight: 2.5,
        description:
          "Incluye herramientas de herrero, carpintero, albañil, etc.",
      },
      {
        name: "Útiles para disfrazarse",
        type: "Tool",
        cost: { quantity: 25, unit: "po" },
        weight: 1.5,
        description:
          "Cosméticos, tintes de pelo y pequeñas prendas para cambiar de apariencia.",
      },
      {
        name: "Útiles para falsificar",
        type: "Tool",
        cost: { quantity: 15, unit: "po" },
        weight: 2.5,
        description: "Tintas, papeles y sellos para crear documentos falsos.",
      },
      {
        name: "Herramientas de navegante",
        type: "Tool",
        cost: { quantity: 25, unit: "po" },
        weight: 1,
        description: "Instrumentos para orientarse en el mar o la naturaleza.",
      },
      {
        name: "Juego",
        type: "Tool",
        cost: { quantity: 1, unit: "po" },
        weight: 0,
        description: "Dados, naipes o piezas de ajedrez dragón.",
      },

      // ===========================================================================
      // 4. EQUIPO DE AVENTURAS (GEAR)
      // ===========================================================================
      {
        name: "Abrojos (bolsa)",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 1,
        description:
          "Cubren una zona de 1,5m. Causan 1 de daño y reducen velocidad.",
      },
      {
        name: "Aceite (frasco)",
        type: "Gear",
        cost: { quantity: 1, unit: "pp" },
        weight: 0.5,
        description: "Se puede lanzar o usar como combustible para lámparas.",
      },
      {
        name: "Ácido (vial)",
        type: "Gear",
        cost: { quantity: 25, unit: "po" },
        weight: 0.5,
        description:
          "Se puede lanzar como arma improvisada. Causa 2d6 de daño de ácido.",
      },
      {
        name: "Agua bendita (frasco)",
        type: "Gear",
        cost: { quantity: 25, unit: "po" },
        weight: 0.5,
        description: "Daña a infernales y muertos vivientes (2d6 radiante).",
      },
      {
        name: "Aljaba",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 0.5,
        description: "Puede contener hasta 20 flechas.",
      },
      {
        name: "Antitoxina",
        type: "Gear",
        cost: { quantity: 50, unit: "po" },
        weight: 0.5,
        description: "Ventaja en salvaciones contra veneno por 1 hora.",
      },
      {
        name: "Antorcha",
        type: "Gear",
        cost: { quantity: 1, unit: "pc" },
        weight: 0.5,
        description: "Arde por 1 hora. Luz brillante 6m, tenue 6m.",
      },
      {
        name: "Ariete portátil",
        type: "Gear",
        cost: { quantity: 4, unit: "po" },
        weight: 17.5,
        description: "+4 a pruebas de Fuerza para romper puertas.",
      },
      {
        name: "Bolas de metal (bolsa)",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 1,
        description:
          "Cubren un área de 3m cuadrados. CD 10 Destreza o caer derribado.",
      },
      {
        name: "Cadena (3m)",
        type: "Gear",
        cost: { quantity: 5, unit: "po" },
        weight: 5,
        description: "Tiene 10 PG. Se puede romper con CD 20 de Fuerza.",
      },
      {
        name: "Canalizador Arcano (Bastón/Vara/Cristal)",
        type: "Gear",
        cost: { quantity: 10, unit: "po" },
        weight: 1,
        description: "Foco mágico para hechiceros, brujos y magos.",
      },
      {
        name: "Canalizador Druídico (Muérdago/Tótem)",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 0,
        description: "Foco mágico para druidas y exploradores.",
      },
      {
        name: "Cuerda (Cáñamo)",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 5,
        description: "15 metros. Se puede romper con CD 17 de Fuerza.",
      },
      {
        name: "Cuerda (Seda)",
        type: "Gear",
        cost: { quantity: 10, unit: "po" },
        weight: 2.5,
        description: "15 metros. Más ligera y resistente que el cáñamo.",
      },
      {
        name: "Esposas",
        type: "Gear",
        cost: { quantity: 2, unit: "po" },
        weight: 1,
        description: "CD 20 para escapar o romperlas.",
      },
      {
        name: "Fuego de Alquimista",
        type: "Gear",
        cost: { quantity: 50, unit: "po" },
        weight: 0.5,
        description:
          "Frasco arrojadizo. Al impactar causa 1d4 de daño de fuego cada turno.",
      },
      {
        name: "Libro de Conjuros",
        type: "Gear",
        cost: { quantity: 50, unit: "po" },
        weight: 1.5,
        description:
          "Esencial para los magos. Contiene sus conjuros inscritos.",
      },
      {
        name: "Linterna sorda",
        type: "Gear",
        cost: { quantity: 5, unit: "po" },
        weight: 1,
        description:
          "Emite luz brillante en 9m. Se puede tapar para ocultar la luz.",
      },
      {
        name: "Paquete de Explorador",
        type: "Gear",
        cost: { quantity: 10, unit: "po" },
        weight: 27.5,
        description:
          "Mochila, petate, kit de cocina, yesquero, 10 antorchas, 10 días de raciones, cantimplora y 15m de cuerda.",
      },
      {
        name: "Paquete de Explorador de Mazmorras",
        type: "Gear",
        cost: { quantity: 12, unit: "po" },
        weight: 21,
        description:
          "Mochila, palanqueta, martillo, pitones, antorchas, yesquero, raciones y cantimplora.",
      },
      {
        name: "Paquete de Ladrón",
        type: "Gear",
        cost: { quantity: 16, unit: "po" },
        weight: 20,
        description:
          "Mochila, bolas de metal, cordel, campana, velas, palanqueta, martillo, pitones, linterna sorda, aceite, raciones, yesquero, cantimplora.",
      },
      {
        name: "Poción de Curación",
        type: "Gear",
        rarity: "Common",
        cost: { quantity: 50, unit: "po" },
        weight: 0.25,
        description:
          "Restaura 2d4 + 2 puntos de golpe. Acción adicional para beber.",
      },
      {
        name: "Red",
        type: "Gear",
        cost: { quantity: 1, unit: "po" },
        weight: 1.5,
        description:
          "Apresar criatura Grande o menor. CD 10 Fuerza para escapar. 5 PG.",
      },
      {
        name: "Símbolo Sagrado",
        type: "Gear",
        cost: { quantity: 5, unit: "po" },
        weight: 0.5,
        description: "Foco mágico para clérigos y paladines.",
      },
      {
        name: "Tienda",
        type: "Gear",
        cost: { quantity: 2, unit: "po" },
        weight: 10,
        description: "Refugio para dos personas.",
      },
      {
        name: "Yesquero",
        type: "Gear",
        cost: { quantity: 5, unit: "pp" },
        weight: 0.5,
        description: "Contiene pedernal y acero para encender fuego.",
      },

      // ===========================================================================
      // 5. MONTURAS Y VEHÍCULOS (MOUNT) - Pág. 229
      // ===========================================================================
      {
        name: "Caballo de Guerra",
        type: "Mount",
        cost: { quantity: 400, unit: "po" },
        description:
          "Entrenado para el combate. Puede llevar barda (armadura).",
      },
      {
        name: "Caballo de Monta",
        type: "Mount",
        cost: { quantity: 75, unit: "po" },
        description:
          "Rápido y fiable para viajes, pero no entrenado para pelear.",
      },
      {
        name: "Poni",
        type: "Mount",
        cost: { quantity: 30, unit: "po" },
        description: "Pequeño pero robusto, ideal para medianos o gnomos.",
      },
      {
        name: "Elefante",
        type: "Mount",
        cost: { quantity: 200, unit: "po" },
        description: "Enorme bestia de carga o guerra.",
      },
      {
        name: "Camello",
        type: "Mount",
        cost: { quantity: 50, unit: "po" },
        description: "Resistente para viajes por el desierto.",
      },
      {
        name: "Mula",
        type: "Mount",
        cost: { quantity: 8, unit: "po" },
        description: "Bestia de carga fiable.",
      },
    ];

    await Item.deleteMany({});
    console.log("🧹 Inventario anterior eliminado.");

    await Item.insertMany(itemsData);
    console.log(
      `✨ Se han forjado ${itemsData.length} objetos en la base de datos.`
    );

    process.exit(0);
  } catch (error) {
    console.error("🔥 Error crítico en la forja (Seeder):", error);
    process.exit(1);
  }
};

seedDB();
